# App
spring.application.name=storeYa
server.port=8081

# Postgres (container name: postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/training
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

# Keycloak (container name: keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/training-realm
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=training-realm
keycloak.resource=training
keycloak.credentials.secret=LIhzGeOkwJnCrjgnUGLrxjibheLU0Evg

