# App
spring.application.name=storeYa
server.port=8081
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Postgres (container name: postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/training
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
# Keycloak (container name: keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/training-realm
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=training-realm
keycloak.resource=training
keycloak.credentials.secret=LIhzGeOkwJnCrjgnUGLrxjibheLU0Evg
#Mail send otp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phuongpk12341@gmail.com
spring.mail.password=qgmssdqvvglefdpd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#Cloudinary
cloudinary.cloud_name=dz0dqy62d
cloudinary.api_key=217775823886184
cloudinary.api_secret=QVaMG_3_gq1HmuWm7jGO6PO7hXU
#VnPay
vnpay.tmnCode=WLWYZK7I
vnpay.hashSecret=43IV4I93P9ODQZFKVBE3FJ0HFFVZKWOD
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:4200/payment-result
vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
vnpay.version=2.1.0

